// Package audit provides the core audit logging subsystem for Tackle.
package audit

import (
	"fmt"
	"time"
)

// Category classifies the source domain of an audit event.
type Category string

// Severity indicates the operational importance of an audit event.
type Severity string

// ActorType describes what kind of entity performed the action.
type ActorType string

const (
	// CategoryUserActivity covers all user-initiated actions in the UI and API.
	CategoryUserActivity Category = "user_activity"
	// CategoryEmailEvent covers email delivery pipeline events.
	CategoryEmailEvent Category = "email_event"
	// CategoryInfrastructure covers phishing endpoint infrastructure events.
	CategoryInfrastructure Category = "infrastructure"
	// CategoryRequest covers HTTP requests to phishing endpoints.
	CategoryRequest Category = "request"
	// CategorySystem covers internal application events.
	CategorySystem Category = "system"
	// CategoryCredentialCapture covers credential capture and access events.
	CategoryCredentialCapture Category = "credential_capture"
)

const (
	// SeverityDebug is detailed diagnostic information; not written to audit_logs in production.
	SeverityDebug Severity = "debug"
	// SeverityInfo is normal operational events (successful user actions, state transitions).
	SeverityInfo Severity = "info"
	// SeverityWarning is abnormal but non-critical (failed logins, health check failures, retries).
	SeverityWarning Severity = "warning"
	// SeverityError is failures requiring attention (cloud API errors, SMTP failures).
	SeverityError Severity = "error"
	// SeverityCritical requires immediate attention (panics, data corruption, log tampering).
	SeverityCritical Severity = "critical"
)

const (
	// ActorTypeUser indicates a human user performed the action.
	ActorTypeUser ActorType = "user"
	// ActorTypeSystem indicates the application itself performed the action.
	ActorTypeSystem ActorType = "system"
	// ActorTypeEndpoint indicates a phishing endpoint performed the action.
	ActorTypeEndpoint ActorType = "endpoint"
	// ActorTypeExternal indicates an external system performed the action.
	ActorTypeExternal ActorType = "external"
)

var validCategories = map[Category]bool{
	CategoryUserActivity:   true,
	CategoryEmailEvent:     true,
	CategoryInfrastructure: true,
	CategoryRequest:           true,
	CategorySystem:            true,
	CategoryCredentialCapture: true,
}

var validSeverities = map[Severity]bool{
	SeverityDebug:    true,
	SeverityInfo:     true,
	SeverityWarning:  true,
	SeverityError:    true,
	SeverityCritical: true,
}

var validActorTypes = map[ActorType]bool{
	ActorTypeUser:     true,
	ActorTypeSystem:   true,
	ActorTypeEndpoint: true,
	ActorTypeExternal: true,
}

// LogEntry is a structured audit log event.
// Mandatory fields: Category, Severity, ActorType, Action.
// ID, Timestamp, and Checksum are set by AuditService before insert.
type LogEntry struct {
	// ID is a UUID v4, generated by AuditService at write time.
	ID string
	// Timestamp is UTC; set by AuditService if zero.
	Timestamp time.Time
	// Category classifies the event domain.
	Category Category
	// Severity indicates operational importance.
	Severity Severity
	// ActorType describes the kind of entity that acted.
	ActorType ActorType
	// ActorID is the UUID of the acting entity (nullable).
	ActorID *string
	// ActorLabel is a human-readable name for the actor.
	ActorLabel string
	// Action is a machine-readable identifier, e.g. "auth.login.success".
	Action string
	// ResourceType is the type of resource affected (nullable).
	ResourceType *string
	// ResourceID is the UUID of the affected resource (nullable).
	ResourceID *string
	// Details holds event-specific structured data; sanitized before write.
	Details map[string]any
	// CorrelationID links related events; defaults to own ID for standalone entries.
	CorrelationID string
	// SourceIP is the request source IP address (nullable).
	SourceIP *string
	// SessionID is the session UUID (nullable).
	SessionID *string
	// CampaignID is the campaign UUID (nullable).
	CampaignID *string
	// Checksum is the HMAC-SHA256 of core fields; set by AuditService, never by callers.
	Checksum string
	// PreviousChecksum is the HMAC of the preceding audit entry, forming a hash chain.
	// Set by AuditService, never by callers.
	PreviousChecksum string
}

// Validate checks that all mandatory fields are present and have valid values.
// Returns a non-nil error describing the first validation failure.
func (e *LogEntry) Validate() error {
	if !validCategories[e.Category] {
		return fmt.Errorf("audit: invalid category %q", e.Category)
	}
	if !validSeverities[e.Severity] {
		return fmt.Errorf("audit: invalid severity %q", e.Severity)
	}
	if !validActorTypes[e.ActorType] {
		return fmt.Errorf("audit: invalid actor_type %q", e.ActorType)
	}
	if e.Action == "" {
		return fmt.Errorf("audit: action is required")
	}
	return nil
}
