package reactgen

import (
	"fmt"
	"path/filepath"

	"github.com/evanw/esbuild/pkg/api"
)

// BundleResult holds the javascript and css payloads generated by ESBuild.
type BundleResult struct {
	JS  []byte
	CSS []byte
}

// RunEsbuild takes the absolute path to the temporary directory containing index.tsx
// and transpiles/bundles it using native esbuild, completely avoiding Node.js.
func RunEsbuild(workspaceDir string) (*BundleResult, error) {
	entryPoint := filepath.Join(workspaceDir, "index.tsx")

	options := api.BuildOptions{
		EntryPoints:       []string{entryPoint},
		Bundle:            true,
		MinifyWhitespace:  true,
		MinifyIdentifiers: true,
		MinifySyntax:      true,
		Outdir:            workspaceDir,
		Write:             false, // Return in memory for immediate binary embedding
		External:          []string{"react", "react-dom", "react-dom/client"},
		JSXFactory:        "React.createElement",
		JSXFragment:       "React.Fragment",
		Loader: map[string]api.Loader{
			".tsx": api.LoaderTSX,
			".ts":  api.LoaderTS,
			".jsx": api.LoaderJSX,
			".js":  api.LoaderJS,
			".css": api.LoaderCSS,
		},
	}

	result := api.Build(options)

	if len(result.Errors) > 0 {
		return nil, fmt.Errorf("esbuild compilation failed: %s", result.Errors[0].Text)
	}

	var res BundleResult
	for _, file := range result.OutputFiles {
		if filepath.Ext(file.Path) == ".js" {
			res.JS = file.Contents
		} else if filepath.Ext(file.Path) == ".css" {
			res.CSS = file.Contents
		}
	}

	if len(res.JS) == 0 {
		return nil, fmt.Errorf("esbuild generated no javascript bundle")
	}

	return &res, nil
}
